
 
 
SELECT I.ANIMAL_ID, I.NAME           
FROM ANIMAL_INS I JOIN ANIMAL_OUTS O
ON I.ANIMAL_ID = O.ANIMAL_ID
WHERE TO_CHAR(O.DATETIME - I.DATETIME) > 0
ORDER BY TO_NUMBER(TO_CHAR(O.DATETIME - I.DATETIME)) DESC
FETCH FIRST 2 ROWS ONLY;





 
